export const ACTIVITY_ACTIONS = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE_POST: 'CREATE_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
}

export const ACTIVITY_RESOURCES = {
  AUTH: 'Auth',
  USER: 'User',
  POST: 'Post',
}
